### ISSUE TITLE
Death Chest Causing internal Errors

### ISSUE THREAD

**Issue by Brithim** [knighthat/NoobHelper#4]
![Screenshot from 2022-03-19 14-23-05](https://user-images.githubusercontent.com/22914585/159133766-33a16956-e8ee-4984-b29b-8c3ba1c45839.png)

`.03 14:20:33 [Server] INFO Domestix was slain by crybabypeep
19.03 14:20:36 [Server] INFO Domestix issued server command: /noobhelper lostitems -1489911073
19.03 14:20:36 [Server] ERROR null
19.03 14:20:36 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'noobhelper' in plugin NoobHelper v0.9.1
19.03 14:20:36 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
19.03 14:20:36 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
19.03 14:20:36 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:905) ~[purpur-1.18.2.jar:git-Purpur-1597]
19.03 14:20:36 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2389) ~[?:?]
19.03 14:20:36 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
19.03 14:20:36 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2181) ~[?:?]
19.03 14:20:36 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
19.03 14:20:36 [Server] INFO at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
19.03 14:20:36 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
19.03 14:20:36 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1597]
19.03 14:20:36 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
19.03 14:20:36 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
19.03 14:20:36 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1597]
19.03 14:20:36 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1597]
19.03 14:20:36 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
19.03 14:20:36 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1597]
19.03 14:20:36 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1597]
19.03 14:20:37 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
19.03 14:20:37 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1597]
19.03 14:20:37 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1597]
19.03 14:20:37 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1597]
19.03 14:20:37 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
19.03 14:20:37 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "String.toCharArray()" because "textToTranslate" is null
19.03 14:20:37 [Server] INFO at net.md_5.bungee.api.ChatColor.translateAlternateColorCodes(ChatColor.java:216) ~[bungeecord-chat-1.16-R0.4-deprecated+build.6.jar:?]
19.03 14:20:37 [Server] INFO at me.knighthat.plugin.utils.TextModification.addColor(TextModification.java:8) ~[NoobHelper.jar:?]
19.03 14:20:37 [Server] INFO at me.knighthat.plugin.Files.Files.getString(Files.java:17) ~[NoobHelper.jar:?]
19.03 14:20:37 [Server] INFO at me.knighthat.plugin.Menus.ShowLostItems.getTitle(ShowLostItems.java:24) ~[NoobHelper.jar:?]
19.03 14:20:37 [Server] INFO at me.knighthat.plugin.Menus.MenuAbstract.open(MenuAbstract.java:83) ~[NoobHelper.jar:?]
19.03 14:20:37 [Server] INFO at me.knighthat.plugin.Commands.LostItems.onCommand(LostItems.java:56) ~[NoobHelper.jar:?]
19.03 14:20:37 [Server] INFO at me.knighthat.plugin.Commands.Manager.onCommand(Manager.java:53) ~[NoobHelper.jar:?]
19.03 14:20:37 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
19.03 14:20:37 [Server] INFO ... 21 more
19.03 14:20:45 [Server]  [Slimefun] Attempted to refresh skin cache, got this response: TimeoutException: null
19.03 14:20:45 [Server]  [Slimefun] This usually means mojang.com is temporarily down or started to rate-limit this connection, nothing to worry about!`

**Comment by knighthat** [comment]
Hi @Brithim, I was able to locate the problem. The new update will be posted after 6 p.m CT. Thank you for reporting the problem
